SRE-2537: add license as expected by OpenSSF Scorecard
daos-stack/fuse3 pull request #13
Opened 2024-10-02 15:47 UTC by grom72

Inherit BSD-2-Clause-Patent License
from the main (daos-stack/daos) project.

2024-10-02 18:15 UTC, osalyk submitted a review, later dismissed

2024-10-04 07:53 UTC, janekmi requested changes

2024-10-04 07:53 UTC, janekmi commented on Makefile
> +# Copyright (c) 2019-2024 Intel Corporation
```suggestion
# Copyright (c) 2019-2024 Intel Corporation

```

2024-10-04 09:58 UTC, grom72 commented on Makefile
> +# Copyright (c) 2019-2024 Intel Corporation
Done

2024-10-04 10:11 UTC, janekmi submitted a review, later dismissed

2024-10-04 11:00 UTC, osalyk submitted a review, later dismissed

2024-10-07 18:02 UTC, brianjmurrell requested changes
Pity that 58600dc67f2d28233b2b40001eff570561e95bed was not pushed to 5e275055a78de3de01d146e44a544256c354be47 as we usually do to overwrite the read-only notice.  Please add a revert of 20039197213d3026c494f5e38fa87fce2a81eab5 to this PR to remove that erroneous message.

2024-10-07 21:18 UTC, grom72 commented
> Pity that [58600dc](https://github.com/daos-stack/fuse3/commit/58600dc67f2d28233b2b40001eff570561e95bed) was not pushed to [5e27505](https://github.com/daos-stack/fuse3/commit/5e275055a78de3de01d146e44a544256c354be47) as we usually do to overwrite the read-only notice. Please add a revert of [2003919](https://github.com/daos-stack/fuse3/commit/20039197213d3026c494f5e38fa87fce2a81eab5) to this PR to remove that erroneous message.

Done

2024-10-08 13:15 UTC, brianjmurrell approved these changes

2024-10-08 13:15 UTC, brianjmurrell approved these changes

2024-10-08 13:16 UTC, merged